### PR TITLE
Integrate the GA with API keys

### PR DESCRIPTION
**Pull request by lamtu1**
Add in the `Google Analytics` key to the YML file to see if this fix the `Scholars Archive` analytics.
#2442

### CODE REVIEW

**Comment by lamtu1** [comment]
@wickr I have gotten a chance to look at it, and Corey and I also sit down and talk about it. We look through `hyrax.rb` and thought it is connecting to GA via in `hyrax.rb` to send data on to GA from Scholars Archive. Because what we discover that GA doesn't automatically send data back to Scholars Archive to update it on SA end, we thought adding this back in might fix it. But I can run through with it with Corey once more on this situation.

**Comment by wickr** [comment]
Ok, I see what you're saying. But if this file was never actually used, but the system of retrieving analytics data worked up until a bit ago, I would think it's something else.

**Comment by CGillen** [comment]
I'm not convinced it was working until a little bit ago. @carakey @simholt any idea how long analytics have been out of sync?

As far as I can tell, the stats were synced from dspace ~6 years ago, then stopped updating around Jan 2022 for some reason.

From what I can trace, Hyrax attempts to pull analytics from GA, failing that they use `::FileDownloadStat` which I can't find where they're generated besides our `process_legacy_stats` rake task that did the dspace syncing. Comments to the analytics code claim `Hyrax::Download` objects are pushed to GA as events, I'm assuming for consumption later to build these analytics pages

**Comment by wickr** [comment]
I'm guessing we lost another config or an API key (`.p12` file) somewhere along the way, or something got messed up with the database on our end.

Or, there was a Rake task running for stats, but it didn't get included in one of the system migrations. There might be helpful info here: https://github.com/uclibs/scholar_uc_legacy/issues/1767

**Comment by simholt** [comment]
@CGillen No idea, they have been problematic off and on since the move to Hyrax.

**Comment by carakey** [comment]
@CGillen All I can say for sure is that it was reported as busted by an OSU faculty on March 13.

**Review by CGillen — APPROVED** [review]

**Pull request merged**
