### PR TITLE
Revert the changes and commented out the YML

### PR DESCRIPTION
**Pull request by lamtu1**
Revert and comment out the stuff push onto YML file.

### CODE REVIEW

**Comment by lamtu1** [comment]
After Meeting
- `Currently:` Pushing the `_ga.html.erb` file with the new code to see if it works with GA4 and if it is tracking in prod
- `Next Step:`
    1. Waiting to see where `Legato` is at and see if it is on track to implement with GA4
    2. Rewrite the code to pull the info from GA4 into Scholars Archive analytics once GA4 is there in Hyrax & Legato

**Comment by CGillen** [comment]
Can you comment out these lines?
https://github.com/osulp/Scholars-Archive/blob/main/.circleci/config.yml#L240-L244

Then we can push an image to staging without committing these changes to main and leave us with an undeployable main branch.

**Comment by CGillen** [comment]
I've converted this to a draft PR to prevent an accidental merge, until we get this tested

**Comment by CGillen** [comment]
Analytics file/dashboard is broken by GA4. PR no longer necessary until dashboard is fixed

**Pull request closed without merging**
