### PR TITLE
Revise the 'remove' button in geo section

### PR DESCRIPTION
**Pull request by lamtu1**
`IN PROGRESS:` Replace the `remove` button with the `trash can icon` instead of the text display the `remove` in the geo section.

### CODE REVIEW

**Comment by lamtu1** [comment]
fixes #1799

**Review by straleyb — APPROVED** [review]

**Comment by lamtu1** [comment]
@straleyb this PR is on hold due to another section needed to be fix that depend on another ticket that still in review. We don't need to merge this one in right now.

**Comment by simholt** [comment]
@lamtu1 What is the status on this one?

**Comment by lamtu1** [comment]
Hi @simholt, would you like me to revisit this and get the display to merge in?

**Comment by simholt** [comment]
@lamtu1 if possible, yes!

**Pull request merged**
