### PR TITLE
Feature/update logo

### LINKED ISSUE #845: Get OSU Logo on Banner
need to get the OSU Logo on the top left of the banner - instead of the little globe.

### LINKED ISSUE #848: set lower banner border to match OSU branding
to match web branding. 

http://communications.oregonstate.edu/brand-guide

may want to talk to @KennaW about details

### LINKED ISSUE #905: send button on contact form is jacked
button is sitting in a weird place, half obscured by the footer. 

screen shot 2017-09-08 at 3 14 52 pm

### PR DESCRIPTION
**Pull request by luisgreg99**
fixes #845 
fixes #905 
fixes #848 

full screen:
image
mobile:
image

### CODE REVIEW

**Comment by revgum** [comment]
@vantuyls I feel like the osu logo with text scholarsarchive@osu is funky.. maybe the logo could be somewhat smaller..and the text align in the center of the height of the logo? It just looks a little "off" to me..

**Comment by vantuyls** [comment]
hrm, this is related to the original intent of: https://github.com/osulp/Scholars-Archive/issues/848 which was to set the lower border of the banner to include the black bar, which is where ScholarsARchive@OSU would live. 

Sorry, bad spec. See example below. How do we move forward? @revgum @luisgreg99 

screen shot 2017-09-19 at 11 45 14 am

**Comment by luisgreg99** [comment]
@vantuyls That makes sense. Here's an updated version of the header:
full screen:
image
mobile:
image

**Comment by vantuyls** [comment]
@luisgreg99 looks good. thanks!

**Pull request merged**
