### PR TITLE
enable statistics dashboard for admin

### PR DESCRIPTION
**Pull request by zhang4952**

### CODE REVIEW

**Comment by straleyb** [comment]
Can you explain what this initializer and changing the solr config is supposed to do? Is this supposed to allow access to a specific webpage?

**Comment by zhang4952** [comment]
config admin_stats initializer:
required to make statistics dashboard available for admin
solrconfig.xml:
add termComponent because it is used by statistics dashboard

**Comment by straleyb** [comment]
Ok! If its a route thats normally unavailable to normal users but available to admins, Id like to see a test for that.

**Comment by vantuyls** [comment]
Wait, is this done? It's not running right now? If this isn't completed we need to move it back to a different column...

**Comment by straleyb** [comment]
When we merged it, it auto closed the ticket I think. Ill move it to in progress and change the verbage.

**Pull request merged**
