### PR TITLE
Add in redirect for fileset

### PR DESCRIPTION
**Pull request by lamtu1**
Add in the redirect to display message for the fileset that is under embargo.

### CODE REVIEW

**Comment by CGillen** [comment]
https://github.com/osulp/Scholars-Archive/blob/main/app/controllers/application_controller.rb#L12
It looks like you were right to be digging around the base applicationcontroller. This might be overboard however. This will redirect every restricted item to the homepage & it includes a huge override for us to maintain.
We already have a monkey patch into the fileset controller, lets use that to narrow this down and not take on any more maintenance workload
https://github.com/osulp/Scholars-Archive/blob/main/config/initializers/hacks/hyrax_file_sets_controller_hack.rb

**Review by CGillen — CHANGES_REQUESTED** [review]
https://github.com/osulp/Scholars-Archive/blob/main/app/controllers/application_controller.rb#L12
It looks like you were right to be digging around the base applicationcontroller. This might be overboard however. This will redirect every restricted item to the homepage & it includes a huge override for us to maintain.
We already have a monkey patch into the fileset controller, lets use that to narrow this down and not take on any more maintenance workload
https://github.com/osulp/Scholars-Archive/blob/main/config/initializers/hacks/hyrax_file_sets_controller_hack.rb

**Comment by lamtu1** [comment]
@CGillen From what I understand is instead of working on the `controller.rb` and fixing the route in that, that would have a huge override for file sets. So rather than going to `controller.rb`, We already have the code fix for file sets in the `hack` you mention and use that to find a way to redirect with that show page in the hack?

**Comment by CGillen** [comment]
Yes, `controller.rb` is a lot to maintain and check when we go for an update. the `file set controller hack` already allows you access to the fileset controller directly, so anything you write in there can be an override anywhere in the fileset controller hierarchy

**Review by CGillen — APPROVED** [review]

**Comment by lamtu1** [comment]
fixes #2505

**Pull request merged**
