### PR TITLE
Dockerize app

### PR DESCRIPTION
**Pull request by revgum**
Transitions SA to fully dockerized, see README for details.

### CODE REVIEW

**Comment by luisgreg99** [comment]
@revgum I tested the PR and the README instructions, and I got `docker-compose build` finishing successfully. 
I only had to cleanup my `/tmp/uploads/hyrax/uploaded_file/file` and `/log` folders to build it and prevent the error `ERROR: Service 'app' failed to build: Error processing tar file(exit status 1): write /data/...: no space left on device`.
I think I had too many files in these folders that was preventing the build.

When I run `docker-compose up`, so far, I'm getting this error 
```
ERROR: for scholarsarchive_lb_1  Cannot start service lb: driver failed programming external connectivity on endpoint scholarsarchive_lb_1
```

**Comment by revgum** [comment]
You might try `docker system prune` as well.

**Comment by luisgreg99** [comment]
Nice, I tested the README instructions for the debugging part and got the rdebug-ide part working well for me using RubyMine.

**Comment by luisgreg99** [comment]
I found these notes helpful when checking out updates for the `hyrax210` branch:

- Running the containers in debug mode tends to slow down the browsing experience. I set my docker settings `Memory` to `8.0 GiB` and `Swap` to `2.0 GiB` to improve my debugging.
- Increased the http timeout flag to `600`:  `COMPOSE_HTTP_TIMEOUT=600 RAILS_ENV=development docker-compose up`

**Comment by revgum** [comment]
@luisgreg99 Yea!! So good! I totally forgot I jacked up my settings for better perf. We'll add notes to the README!

**Pull request merged**
