### PR TITLE
update config schema

### PR DESCRIPTION
**Pull request by luisgreg99**
Update solr config schema to address solr exception on fresh docker build:
```
RSolr::Error::Http - 500 Internal Server Error Error: { "error":{ "metadata":[ "error-class","org.apache.solr.core.SolrCoreInitializationException", "root-error-class","java.lang.ClassNotFoundException"], "msg":"SolrCore 'hydra-development' is not available due to init failure: 
```

### CODE REVIEW

**Comment by straleyb** [comment]
Ive ran `docker system prune` and `docker-compose build` multiple times, and I cant seem to get this error to pop up. Can you write steps to reproduce this error?

**Comment by wickr** [comment]
@straleyb 	did you have luck doing `docker-compose up server` ?  docker-compose build is fine, but Solr has issues on startup due to the conf files

**Comment by wickr** [comment]
I rebuilt again and Solr seems to start up within Docker without issues. (though I can't create a work yet to check, workflows don't seem to want to load)

**Comment by straleyb** [comment]
Stale, If we run into this issue again, we can revisit this.

**Pull request closed without merging**
